name: DataMiner CICD NuGet Solution

on:
  push:
    branches:
      - '**'
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-**"
  workflow_dispatch:

jobs:
  CICD:
    uses: SaraSA10/_ReusableWorkflows/.github/workflows/main.yml@main
    with:
      solution-path: '${{ github.workspace }}/MySolution.sln'
      output-directory: '${{ github.workspace }}/mcc-results'  
      catalog-id: 'f085ba56-de3f-42e6-97a5-566d05d5f325'
      output-format: 'JSON,HTML'
    secrets:
      catalog-api-key: ${{ secrets.CATALOG_API_KEY }}

  export:
    if: github.ref_type == 'tag'
    needs: CICD
    name: Export Error Messages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      
      - name: Building
        run: dotnet build "./ExportErrorMessages/ExportErrorMessages.csproj" --configuration Release -nodeReuse:false --output ./publish

      - name: Create TEMP directory
        run: mkdir -p ./TEMP

      - name: Run export logic
        run: | 
          dotnet ./publish/ExportErrorMessages.dll ./Protocol/ErrorMessages.xml ${{ github.ref_name }} ./TEMP

      - name: Update release
        uses: ncipollo/release-action@v1.14.0
        with:
          name: Release v${{ github.ref_name }}
          allowUpdates: true
          artifacts: "./TEMP/Validator Error Messages - ${{ github.ref_name }}.xlsx"
          omitBodyDuringUpdate: true
